trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    exclude:
    - .github/*
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: npm ci
    displayName: 'Install'

  - script: npm run build
    displayName: 'Build'

  - script: npm test
    displayName: 'Test'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
    displayName: 'Create file archive to publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish files to Azure Pipelines'
